/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardTemplatesRouteImport } from './routes/dashboard/templates'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardResumesRouteImport } from './routes/dashboard/resumes'
import { Route as DashboardJobMatcherRouteImport } from './routes/dashboard/job-matcher'
import { Route as DashboardCoverLettersRouteImport } from './routes/dashboard/cover-letters'
import { Route as DashboardBillingRouteImport } from './routes/dashboard/billing'
import { Route as DashboardAtsRouteImport } from './routes/dashboard/ats'
import { Route as DashboardResumesIdRouteImport } from './routes/dashboard/resumes.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTemplatesRoute = DashboardTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardResumesRoute = DashboardResumesRouteImport.update({
  id: '/resumes',
  path: '/resumes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardJobMatcherRoute = DashboardJobMatcherRouteImport.update({
  id: '/job-matcher',
  path: '/job-matcher',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardCoverLettersRoute = DashboardCoverLettersRouteImport.update({
  id: '/cover-letters',
  path: '/cover-letters',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardAtsRoute = DashboardAtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardResumesIdRoute = DashboardResumesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardResumesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/ats': typeof DashboardAtsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/cover-letters': typeof DashboardCoverLettersRoute
  '/dashboard/job-matcher': typeof DashboardJobMatcherRoute
  '/dashboard/resumes': typeof DashboardResumesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/resumes/$id': typeof DashboardResumesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/ats': typeof DashboardAtsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/cover-letters': typeof DashboardCoverLettersRoute
  '/dashboard/job-matcher': typeof DashboardJobMatcherRoute
  '/dashboard/resumes': typeof DashboardResumesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/resumes/$id': typeof DashboardResumesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard/ats': typeof DashboardAtsRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/cover-letters': typeof DashboardCoverLettersRoute
  '/dashboard/job-matcher': typeof DashboardJobMatcherRoute
  '/dashboard/resumes': typeof DashboardResumesRouteWithChildren
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/templates': typeof DashboardTemplatesRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/resumes/$id': typeof DashboardResumesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/ats'
    | '/dashboard/billing'
    | '/dashboard/cover-letters'
    | '/dashboard/job-matcher'
    | '/dashboard/resumes'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/'
    | '/dashboard/resumes/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/ats'
    | '/dashboard/billing'
    | '/dashboard/cover-letters'
    | '/dashboard/job-matcher'
    | '/dashboard/resumes'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard'
    | '/dashboard/resumes/$id'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/dashboard/ats'
    | '/dashboard/billing'
    | '/dashboard/cover-letters'
    | '/dashboard/job-matcher'
    | '/dashboard/resumes'
    | '/dashboard/settings'
    | '/dashboard/templates'
    | '/dashboard/'
    | '/dashboard/resumes/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/templates': {
      id: '/dashboard/templates'
      path: '/templates'
      fullPath: '/dashboard/templates'
      preLoaderRoute: typeof DashboardTemplatesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/resumes': {
      id: '/dashboard/resumes'
      path: '/resumes'
      fullPath: '/dashboard/resumes'
      preLoaderRoute: typeof DashboardResumesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/job-matcher': {
      id: '/dashboard/job-matcher'
      path: '/job-matcher'
      fullPath: '/dashboard/job-matcher'
      preLoaderRoute: typeof DashboardJobMatcherRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/cover-letters': {
      id: '/dashboard/cover-letters'
      path: '/cover-letters'
      fullPath: '/dashboard/cover-letters'
      preLoaderRoute: typeof DashboardCoverLettersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/ats': {
      id: '/dashboard/ats'
      path: '/ats'
      fullPath: '/dashboard/ats'
      preLoaderRoute: typeof DashboardAtsRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/resumes/$id': {
      id: '/dashboard/resumes/$id'
      path: '/$id'
      fullPath: '/dashboard/resumes/$id'
      preLoaderRoute: typeof DashboardResumesIdRouteImport
      parentRoute: typeof DashboardResumesRoute
    }
  }
}

interface DashboardResumesRouteChildren {
  DashboardResumesIdRoute: typeof DashboardResumesIdRoute
}

const DashboardResumesRouteChildren: DashboardResumesRouteChildren = {
  DashboardResumesIdRoute: DashboardResumesIdRoute,
}

const DashboardResumesRouteWithChildren =
  DashboardResumesRoute._addFileChildren(DashboardResumesRouteChildren)

interface DashboardRouteRouteChildren {
  DashboardAtsRoute: typeof DashboardAtsRoute
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCoverLettersRoute: typeof DashboardCoverLettersRoute
  DashboardJobMatcherRoute: typeof DashboardJobMatcherRoute
  DashboardResumesRoute: typeof DashboardResumesRouteWithChildren
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTemplatesRoute: typeof DashboardTemplatesRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardAtsRoute: DashboardAtsRoute,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCoverLettersRoute: DashboardCoverLettersRoute,
  DashboardJobMatcherRoute: DashboardJobMatcherRoute,
  DashboardResumesRoute: DashboardResumesRouteWithChildren,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTemplatesRoute: DashboardTemplatesRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.ts'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
